[package]
name = "ssot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
git2 = "0.20.0"
infer = "0.19.0"
octocrab = "0.43.0"
tokio = { version = "1.43.0", features = ["full"] }
walkdir = "2.5.0"
